### ISSUE TITLE
Incorrect MongoDB query building

### ISSUE THREAD

**Issue by akaNightmare** [graphql-compose/graphql-compose-pagination#2]
Hello,

```js
{
  users: userPagination(page: 1, perPage: 1)  {
    items {
      name
    }
    pageInfo {
      currentPage
      pageCount
      perPage
      itemCount
    }
  }
}
```
Mongoose Logs:
`[1] Mongoose: users.find({}, { limit: 2, fields: { items: true, pageInfo: true, name: true } })
`
Limit should be **1**.

**Comment by nodkz** [comment]
You may not request `count` field, so pagination will not send second expensive count query to Database.

This is expected +1 record fetching for checking the presence of next page:
https://github.com/nodkz/graphql-compose-pagination/blob/master/src/paginationResolver.js#L132
You receive data without this record.

Of course, you may improve code to not fetch additional +1 record if
- `count` or `pageInfo.itemCount` or `pageInfo.pageCount` are requested in query via projection
- `hasNextPage` is not requested in projection

PRs welcome ;) But for now it quite fast and performant solution.
