### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ceddybi** [graphql-compose/graphql-compose-pagination#8]
I tried using this lib with typescript and it kept, showing this error `ObjectTypeComposer`, i think it's due to flow. and it doesn't have any ts typings.

## Solution
I got curious and re-wrote it in typescript, and it successfully runs now.

**Comment by ceddybi** [comment]
@nodkz  should I submit a pr for this?

**Comment by nodkz** [comment]
Sure! 👍

**Comment by ceddybi** [comment]
@nodkz Done, please check it out and let me know, thanks
